"""Badge evaluation service for gamified achievements and LeetCode-style mastery."""
from typing import Any, Dict, List, Optional


class BadgeService:
    """Evaluates all 29 gamified badges dynamically across 6 categories."""

    @staticmethod
    def evaluate_badges(
        total_prompts: int,
        user_raw_scores: List[float],
        streak_days: int,
        inbuilt_templates_used: int,
        custom_templates: int,
        max_versions: int,
        unique_models: int,
        unique_modes: int,
    ) -> List[Dict[str, Any]]:
        max_user_score = max(user_raw_scores) if user_raw_scores else 0.0
        score_80_count = sum(1 for s in user_raw_scores if s >= 80.0)

        badges_def = [
            # ── 1. Volume & Craft Milestones (5 Badges) ──────────────────────────
            {
                "id": "prompt-pioneer",
                "title": "Prompt Pioneer",
                "tier": "bronze",
                "category": "Volume & Craft",
                "description": "Created more than 10 prompts",
                "unlock_criterion": "total_prompts > 10",
                "icon": "Sparkles",
                "color": "#CD7F32",
                "unlocked": total_prompts > 10,
                "progress": f"{total_prompts}/11 prompts",
                "percentage": min(100.0, round((total_prompts / 11) * 100, 1)),
            },
            {
                "id": "centurion-crafter",
                "title": "Centurion Crafter",
                "tier": "silver",
                "category": "Volume & Craft",
                "description": "Created more than 100 prompts",
                "unlock_criterion": "total_prompts > 100",
                "icon": "Award",
                "color": "#94A3B8",
                "unlocked": total_prompts > 100,
                "progress": f"{total_prompts}/101 prompts",
                "percentage": min(100.0, round((total_prompts / 101) * 100, 1)),
            },
            {
                "id": "high-volume-architect",
                "title": "High-Volume Architect",
                "tier": "gold",
                "category": "Volume & Craft",
                "description": "Created more than 250 prompts",
                "unlock_criterion": "total_prompts > 250",
                "icon": "Flame",
                "color": "#F59E0B",
                "unlocked": total_prompts > 250,
                "progress": f"{total_prompts}/251 prompts",
                "percentage": min(100.0, round((total_prompts / 251) * 100, 1)),
            },
            {
                "id": "industrial-synthesizer",
                "title": "Industrial Synthesizer",
                "tier": "gold",
                "category": "Volume & Craft",
                "description": "Created more than 500 prompts",
                "unlock_criterion": "total_prompts > 500",
                "icon": "Cpu",
                "color": "#F59E0B",
                "unlocked": total_prompts > 500,
                "progress": f"{total_prompts}/501 prompts",
                "percentage": min(100.0, round((total_prompts / 501) * 100, 1)),
            },
            {
                "id": "grandmaster-scribe",
                "title": "Grandmaster Scribe",
                "tier": "diamond",
                "category": "Volume & Craft",
                "description": "Created more than 1000 prompts",
                "unlock_criterion": "total_prompts > 1000",
                "icon": "Crown",
                "color": "#38BDF8",
                "unlocked": total_prompts > 1000,
                "progress": f"{total_prompts}/1001 prompts",
                "percentage": min(100.0, round((total_prompts / 1001) * 100, 1)),
            },

            # ── 2. Raw Prompt Mastery (5 Badges) ─────────────────────────────────
            {
                "id": "quality-foundationalist",
                "title": "Quality Foundationalist",
                "tier": "bronze",
                "category": "Raw Prompt Mastery",
                "description": "Drafted a raw prompt scoring 60+ points",
                "unlock_criterion": "user_score >= 60",
                "icon": "Target",
                "color": "#CD7F32",
                "unlocked": max_user_score >= 60.0,
                "progress": f"{round(max_user_score, 1)}/60 pts",
                "percentage": min(100.0, round((max_user_score / 60) * 100, 1)),
            },
            {
                "id": "articulate-thinker",
                "title": "Articulate Thinker",
                "tier": "bronze",
                "category": "Raw Prompt Mastery",
                "description": "Drafted a raw prompt scoring 70+ points",
                "unlock_criterion": "user_score >= 70",
                "icon": "Brain",
                "color": "#CD7F32",
                "unlocked": max_user_score >= 70.0,
                "progress": f"{round(max_user_score, 1)}/70 pts",
                "percentage": min(100.0, round((max_user_score / 70) * 100, 1)),
            },
            {
                "id": "master-of-precision",
                "title": "Master of Precision",
                "tier": "silver",
                "category": "Raw Prompt Mastery",
                "description": "Drafted 3+ raw prompts scoring 80+ points",
                "unlock_criterion": "count(user_score >= 80) >= 3",
                "icon": "CheckCircle",
                "color": "#94A3B8",
                "unlocked": score_80_count >= 3,
                "progress": f"{score_80_count}/3 prompts",
                "percentage": min(100.0, round((score_80_count / 3) * 100, 1)),
            },
            {
                "id": "perfectionist",
                "title": "Perfectionist",
                "tier": "gold",
                "category": "Raw Prompt Mastery",
                "description": "Drafted a near-flawless raw prompt scoring 88+ points",
                "unlock_criterion": "user_score >= 88",
                "icon": "Sparkle",
                "color": "#F59E0B",
                "unlocked": max_user_score >= 88.0,
                "progress": f"{round(max_user_score, 1)}/88 pts",
                "percentage": min(100.0, round((max_user_score / 88) * 100, 1)),
            },
            {
                "id": "sovereign-wordsmith",
                "title": "Sovereign Wordsmith",
                "tier": "diamond",
                "category": "Raw Prompt Mastery",
                "description": "Drafted an elite raw prompt scoring 92+ points",
                "unlock_criterion": "user_score >= 92",
                "icon": "Crown",
                "color": "#38BDF8",
                "unlocked": max_user_score >= 92.0,
                "progress": f"{round(max_user_score, 1)}/92 pts",
                "percentage": min(100.0, round((max_user_score / 92) * 100, 1)),
            },

            # ── 3. Consistency & Streak (8 Badges) ───────────────────────────────
            {
                "id": "7-day-spark",
                "title": "7-Day Spark",
                "tier": "bronze",
                "category": "Consistency & Streak",
                "description": "Maintained a 7-day enhancement streak",
                "unlock_criterion": "streak_days >= 7",
                "icon": "Zap",
                "color": "#CD7F32",
                "unlocked": streak_days >= 7,
                "progress": f"{streak_days}/7 days",
                "percentage": min(100.0, round((streak_days / 7) * 100, 1)),
            },
            {
                "id": "fortnight-fortitude",
                "title": "Fortnight Fortitude",
                "tier": "bronze",
                "category": "Consistency & Streak",
                "description": "Maintained a 14-day enhancement streak",
                "unlock_criterion": "streak_days >= 14",
                "icon": "Flame",
                "color": "#CD7F32",
                "unlocked": streak_days >= 14,
                "progress": f"{streak_days}/14 days",
                "percentage": min(100.0, round((streak_days / 14) * 100, 1)),
            },
            {
                "id": "monthly-devotion",
                "title": "Monthly Devotion",
                "tier": "silver",
                "category": "Consistency & Streak",
                "description": "Maintained a 30-day enhancement streak",
                "unlock_criterion": "streak_days >= 30",
                "icon": "Calendar",
                "color": "#94A3B8",
                "unlocked": streak_days >= 30,
                "progress": f"{streak_days}/30 days",
                "percentage": min(100.0, round((streak_days / 30) * 100, 1)),
            },
            {
                "id": "habitual-craftsman",
                "title": "Habitual Craftsman",
                "tier": "silver",
                "category": "Consistency & Streak",
                "description": "Maintained a 60-day enhancement streak",
                "unlock_criterion": "streak_days >= 60",
                "icon": "Compass",
                "color": "#94A3B8",
                "unlocked": streak_days >= 60,
                "progress": f"{streak_days}/60 days",
                "percentage": min(100.0, round((streak_days / 60) * 100, 1)),
            },
            {
                "id": "century-of-consistency",
                "title": "Century of Consistency",
                "tier": "gold",
                "category": "Consistency & Streak",
                "description": "Maintained a 100-day enhancement streak",
                "unlock_criterion": "streak_days >= 100",
                "icon": "Shield",
                "color": "#F59E0B",
                "unlocked": streak_days >= 100,
                "progress": f"{streak_days}/100 days",
                "percentage": min(100.0, round((streak_days / 100) * 100, 1)),
            },
            {
                "id": "iron-discipline",
                "title": "Iron Discipline",
                "tier": "gold",
                "category": "Consistency & Streak",
                "description": "Maintained a 200-day enhancement streak",
                "unlock_criterion": "streak_days >= 200",
                "icon": "Activity",
                "color": "#F59E0B",
                "unlocked": streak_days >= 200,
                "progress": f"{streak_days}/200 days",
                "percentage": min(100.0, round((streak_days / 200) * 100, 1)),
            },
            {
                "id": "the-500-club",
                "title": "The 500 Club",
                "tier": "diamond",
                "category": "Consistency & Streak",
                "description": "Maintained a monumental 500-day streak",
                "unlock_criterion": "streak_days >= 500",
                "icon": "Medal",
                "color": "#38BDF8",
                "unlocked": streak_days >= 500,
                "progress": f"{streak_days}/500 days",
                "percentage": min(100.0, round((streak_days / 500) * 100, 1)),
            },
            {
                "id": "millennial-legend",
                "title": "Millennial Legend",
                "tier": "diamond",
                "category": "Consistency & Streak",
                "description": "Transcended into folklore with a 1000-day streak",
                "unlock_criterion": "streak_days >= 1000",
                "icon": "Award",
                "color": "#38BDF8",
                "unlocked": streak_days >= 1000,
                "progress": f"{streak_days}/1000 days",
                "percentage": min(100.0, round((streak_days / 1000) * 100, 1)),
            },

            # ── 4. Template & Iteration Mastery (3 Badges) ───────────────────────
            {
                "id": "template-apprentice",
                "title": "Template Apprentice",
                "tier": "bronze",
                "category": "Template Mastery",
                "description": "Used inbuilt templates for enhancement 10+ times",
                "unlock_criterion": "inbuilt_templates_used >= 10",
                "icon": "Layout",
                "color": "#CD7F32",
                "unlocked": inbuilt_templates_used >= 10,
                "progress": f"{inbuilt_templates_used}/10 used",
                "percentage": min(100.0, round((inbuilt_templates_used / 10) * 100, 1)),
            },
            {
                "id": "blueprint-architect",
                "title": "Blueprint Architect",
                "tier": "silver",
                "category": "Template Mastery",
                "description": "Created 5+ custom prompt templates",
                "unlock_criterion": "custom_templates >= 5",
                "icon": "FileText",
                "color": "#94A3B8",
                "unlocked": custom_templates >= 5,
                "progress": f"{custom_templates}/5 created",
                "percentage": min(100.0, round((custom_templates / 5) * 100, 1)),
            },
            {
                "id": "iteration-specialist",
                "title": "Iteration Specialist",
                "tier": "bronze",
                "category": "Template Mastery",
                "description": "Created 3+ versions for a single prompt",
                "unlock_criterion": "max_versions >= 3",
                "icon": "GitCommit",
                "color": "#CD7F32",
                "unlocked": max_versions >= 3,
                "progress": f"{max_versions}/3 versions",
                "percentage": min(100.0, round((max_versions / 3) * 100, 1)),
            },

            # ── 5. Model Explorer (4 Badges) ─────────────────────────────────────
            {
                "id": "dual-channel",
                "title": "Dual Channel",
                "tier": "bronze",
                "category": "Model Explorer",
                "description": "Enhanced prompts targeting 2+ AI models",
                "unlock_criterion": "unique_models >= 2",
                "icon": "Share2",
                "color": "#CD7F32",
                "unlocked": unique_models >= 2,
                "progress": f"{unique_models}/2 models",
                "percentage": min(100.0, round((unique_models / 2) * 100, 1)),
            },
            {
                "id": "multi-model-pilot",
                "title": "Multi-Model Pilot",
                "tier": "silver",
                "category": "Model Explorer",
                "description": "Enhanced prompts targeting 4+ AI models",
                "unlock_criterion": "unique_models >= 4",
                "icon": "Layers",
                "color": "#94A3B8",
                "unlocked": unique_models >= 4,
                "progress": f"{unique_models}/4 models",
                "percentage": min(100.0, round((unique_models / 4) * 100, 1)),
            },
            {
                "id": "cross-llm-polyglot",
                "title": "Cross-LLM Polyglot",
                "tier": "gold",
                "category": "Model Explorer",
                "description": "Enhanced prompts targeting 6+ AI models",
                "unlock_criterion": "unique_models >= 6",
                "icon": "Globe",
                "color": "#F59E0B",
                "unlocked": unique_models >= 6,
                "progress": f"{unique_models}/6 models",
                "percentage": min(100.0, round((unique_models / 6) * 100, 1)),
            },
            {
                "id": "universal-conductor",
                "title": "Universal Conductor",
                "tier": "diamond",
                "category": "Model Explorer",
                "description": "Enhanced prompts targeting 8+ AI models",
                "unlock_criterion": "unique_models >= 8",
                "icon": "Command",
                "color": "#38BDF8",
                "unlocked": unique_models >= 8,
                "progress": f"{unique_models}/8 models",
                "percentage": min(100.0, round((unique_models / 8) * 100, 1)),
            },

            # ── 6. Mode & Versatility (4 Badges) ─────────────────────────────────
            {
                "id": "multi-dimensional",
                "title": "Multi-Dimensional",
                "tier": "bronze",
                "category": "Mode & Versatility",
                "description": "Used 2+ distinct enhancement styles or modes",
                "unlock_criterion": "unique_modes >= 2",
                "icon": "Sliders",
                "color": "#CD7F32",
                "unlocked": unique_modes >= 2,
                "progress": f"{unique_modes}/2 modes",
                "percentage": min(100.0, round((unique_modes / 2) * 100, 1)),
            },
            {
                "id": "style-synthesizer",
                "title": "Style Synthesizer",
                "tier": "silver",
                "category": "Mode & Versatility",
                "description": "Used 4+ distinct enhancement styles or modes",
                "unlock_criterion": "unique_modes >= 4",
                "icon": "Filter",
                "color": "#94A3B8",
                "unlocked": unique_modes >= 4,
                "progress": f"{unique_modes}/4 modes",
                "percentage": min(100.0, round((unique_modes / 4) * 100, 1)),
            },
            {
                "id": "full-spectrum-engineer",
                "title": "Full-Spectrum Engineer",
                "tier": "gold",
                "category": "Mode & Versatility",
                "description": "Used 6+ distinct enhancement styles or modes",
                "unlock_criterion": "unique_modes >= 6",
                "icon": "Grid",
                "color": "#F59E0B",
                "unlocked": unique_modes >= 6,
                "progress": f"{unique_modes}/6 modes",
                "percentage": min(100.0, round((unique_modes / 6) * 100, 1)),
            },
            {
                "id": "omnipresent-architect",
                "title": "Omnipresent Architect",
                "tier": "diamond",
                "category": "Mode & Versatility",
                "description": "Mastered all 8+ enhancement styles or modes",
                "unlock_criterion": "unique_modes >= 8",
                "icon": "Zap",
                "color": "#38BDF8",
                "unlocked": unique_modes >= 8,
                "progress": f"{unique_modes}/8 modes",
                "percentage": min(100.0, round((unique_modes / 8) * 100, 1)),
            },
        ]

        return badges_def
