"""replace total_score with old_analysis and new_analysis

Revision ID: 9614bbfec30b
Revises: af3e6b17c00b
Create Date: 2026-08-07 17:10:29.269154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9614bbfec30b'
down_revision: Union[str, None] = 'af3e6b17c00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('new_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('total_score')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('new_analysis')
        batch_op.drop_column('old_analysis')

    # ### end Alembic commands ###
