"""create style profiles table

Revision ID: 9a2bc840512d
Revises: 0002_create_promptiq_tables
Create Date: 2026-06-24 13:27:12.816937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a2bc840512d'
down_revision: Union[str, None] = '0002_create_promptiq_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('style_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('injection_template', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('use_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("type IN ('character', 'cinematic', 'art_style', 'environment', 'brand_voice')", name='valid_type_constraint'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('profiles_email_key'), type_='unique')

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index('ix_templates_ai_model_id', ['ai_model_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index('ix_templates_ai_model_id')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('profiles_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    op.drop_table('style_profiles')
    # ### end Alembic commands ###
