"""
StubLLMProvider — a deterministic BaseLLMProvider for tests.

WHY A STUB AND NOT A MOCK OF MistralProvider
--------------------------------------------
Every LLM-touching service takes a ``BaseLLMProvider`` through the constructor
and is wired with ``Depends(get_llm_provider)``, so replacing that one
dependency reaches the entire graph. Patching ``MistralProvider``'s methods
would instead couple the tests to one concrete provider and to the exact
wording of the prompts it is handed.

HOW ``generate()`` DECIDES WHAT TO RETURN
----------------------------------------
``generate()`` is shared by five callers that each demand a *different* JSON
shape, and the provider only ever sees one string. Rather than sniff the user's
prompt text (fragile — it changes whenever a user types something else), the
stub keys off the **response contract the caller itself declares** in its own
instruction block: ``PromptAnalysisService`` spells out ``"role_definition"``,
``PromptComparisonService`` spells out ``"quality_delta"``, and so on. Those key
names are part of the caller's contract with the model, so they are exactly as
stable as the parsing code that consumes the reply.

If a caller's contract changes, ``ROUTES`` stops matching and the prompt is
recorded in :attr:`StubLLMProvider.unrouted_prompts` — tests assert that list is
empty, so drift surfaces as a clear failure instead of a mystery 500.

DETERMINISM CONSTRAINTS WORTH KNOWING
-------------------------------------
``PromptEnhancementService.is_task_execution`` rejects any optimized output that
starts with a conversational header ("here is", "sure, here", …) or that
contains none of its directive keywords ("act as", "you are", "objective:", …).
An output that trips it sends the blocking path into ``max_retries`` rounds of
exponential backoff before failing. :data:`DEFAULT_OPTIMIZED_PROMPT` is written
to satisfy both rules, so keep any replacement directive-shaped.
"""

from __future__ import annotations

import json
from collections.abc import AsyncIterator
from dataclasses import dataclass, field
from typing import Any, Callable, Optional

from app.services.llm.base import BaseLLMProvider
from app.services.llm.schemas import (
    GenerationResult,
    HealthCheckResult,
    PromptAnalysisResult,
    PromptOptimizationResult,
)

# ── Canned optimized output ───────────────────────────────────────────────
# Opens with "You are" so is_task_execution() sees a directive, and does NOT
# start with any conversational header. Contains no "ENHANCED PROMPT:" marker,
# so _clean_enhanced_output() passes it through unchanged and tests can compare
# the response against this constant exactly.
DEFAULT_OPTIMIZED_PROMPT = (
    "You are an expert assistant.\n"
    "Objective: produce the deliverable the user described.\n"
    "Context: this text is generated by the deterministic test stub.\n"
    "Constraints: be specific, cite assumptions, and return Markdown."
)

# ── Analysis fixture ──────────────────────────────────────────────────────
# Per-dimension scores are distinct so a test can detect a dimension being read
# from the wrong slot. The weights applied by PromptAnalysisService are
# clarity .20, context .20, role_definition .15, output_format .15,
# constraints .15, examples .15 — chosen here to land on a whole number, which
# avoids depending on Python's banker's rounding at the .5 boundary.
STUB_ANALYSIS_SCORES: dict[str, int] = {
    "clarity": 90,
    "context": 80,
    "role_definition": 80,
    "output_format": 80,
    "constraints": 60,
    "examples": 60,
}
# 90*.20 + 80*.20 + 80*.15 + 80*.15 + 60*.15 + 60*.15 = 76
STUB_ANALYSIS_OVERALL_SCORE = 76
STUB_ANALYSIS_GRADE = "C+"

# Comparison fixture. grade_improvement is parsed by enhancement.py with
# .split(" to ")[-1] to derive the stored grade, so the " to " separator and the
# trailing grade both matter.
STUB_COMPARISON_GRADE_BEFORE = "D"
STUB_COMPARISON_GRADE_AFTER = "A"

STUB_CLASSIFICATION_LEVEL = "standard"
STUB_CLASSIFICATION_REASON = "Deterministic stub classification."

# Prefix on any generate() reply the routing table did not recognise. Present so
# an unrouted call is visible in assertion output rather than looking like a
# plausible model answer.
UNROUTED_MARKER = "[stub-llm: unrouted generate() call]"


def _analysis_payload() -> str:
    return json.dumps(
        {
            "summary": "Deterministic stub analysis.",
            "dimensions": {
                name: {
                    "score": score,
                    "explanation": f"Stub explanation for {name}.",
                    "suggestions": [f"Stub suggestion for {name}."],
                }
                for name, score in STUB_ANALYSIS_SCORES.items()
            },
        }
    )


def _comparison_payload() -> str:
    return json.dumps(
        {
            "differences": "The enhanced prompt adds role, context and constraints.",
            "improvements": ["Added an explicit role.", "Added output constraints."],
            "missing_issues_fixed": ["Missing role definition.", "Missing output format."],
            "quality_delta": 4.0,
            "readability_improvement": "Structured into labelled sections.",
            "summary": {
                "before_score": 4.5,
                "after_score": 8.5,
                "score_improvement": 4.0,
                "grade_improvement": (
                    f"{STUB_COMPARISON_GRADE_BEFORE} to {STUB_COMPARISON_GRADE_AFTER}"
                ),
                "estimated_quality_increase_pct": 88.5,
                "confidence": 0.95,
            },
        }
    )


def _classification_payload() -> str:
    return json.dumps(
        {"level": STUB_CLASSIFICATION_LEVEL, "reason": STUB_CLASSIFICATION_REASON}
    )


def _intent_payload() -> str:
    # Both null on purpose: IntentAnalysisService then falls back to whatever
    # role/mode the caller already had, which keeps template retrieval driven by
    # the test's explicit inputs instead of by the stub's guesswork.
    return json.dumps({"inferred_role": None, "inferred_mode": None})


def _merged_prompt_payload(prompt: str) -> str:
    # PromptRegenerationService asks for the merged prompt as bare text. Echo
    # the feedback line back so a test can prove the merge step ran.
    for line in prompt.splitlines():
        if line.startswith("Original Prompt:"):
            original = line[len("Original Prompt:") :].strip()
            return f"{original} (stub-merged feedback)"
    return "Stub merged prompt."


# Ordered (name, marker, builder). The marker is a substring of the *caller's*
# declared response contract, never of the end user's prompt.
ROUTES: tuple[tuple[str, str, Callable[[str], str]], ...] = (
    # PromptAnalysisService.ANALYSIS_PROMPT_TEMPLATE
    ("analysis", '"role_definition"', lambda _prompt: _analysis_payload()),
    # PromptComparisonService.COMPARISON_PROMPT_TEMPLATE
    ("comparison", '"quality_delta"', lambda _prompt: _comparison_payload()),
    # PromptClassificationService._CLASSIFIER_PROMPT
    ("classification", '"level": "minimal"', lambda _prompt: _classification_payload()),
    # IntentAnalysisService.analyze_intent
    ("intent", "inferred_role", lambda _prompt: _intent_payload()),
    # PromptRegenerationService feedback merge
    ("merge", "produce a single merged prompt", _merged_prompt_payload),
)


@dataclass
class RecordedCall:
    """One provider invocation, for assertions about what the app asked for."""

    method: str
    prompt: str
    kwargs: dict[str, Any] = field(default_factory=dict)
    route: Optional[str] = None


class StubLLMProvider(BaseLLMProvider):
    """Deterministic provider. One instance is shared per test.

    Test-facing knobs:

    * :attr:`calls` — every invocation in order.
    * :attr:`unrouted_prompts` — ``generate()`` prompts no route matched.
    * :meth:`set_optimized_prompt` — change what ``optimize_prompt`` returns.
    * :meth:`set_stream_chunks` — control the exact SSE token boundaries.
    * :meth:`fail` — make one method raise, to exercise error paths.
    * :meth:`override_generate` — force a specific ``generate()`` reply
      (e.g. malformed JSON) for one route.
    """

    def __init__(
        self,
        *,
        optimized_prompt: str = DEFAULT_OPTIMIZED_PROMPT,
        stream_chunks: Optional[list[str]] = None,
    ) -> None:
        self.calls: list[RecordedCall] = []
        self.unrouted_prompts: list[str] = []
        self._optimized_prompt = optimized_prompt
        self._stream_chunks: Optional[list[str]] = (
            list(stream_chunks) if stream_chunks is not None else None
        )
        self._failures: dict[str, BaseException] = {}
        self._generate_overrides: dict[str, str] = {}

    # ── Test-facing configuration ─────────────────────────────────────────

    def set_optimized_prompt(self, text: str) -> None:
        self._optimized_prompt = text

    def set_stream_chunks(self, chunks: list[str]) -> None:
        """Pin the exact deltas ``optimize_prompt_stream`` yields.

        Their concatenation becomes the final enhanced prompt, so a stream test
        can assert both the individual frames and the assembled result.
        """
        self._stream_chunks = list(chunks)

    def fail(self, method: str, exc: BaseException) -> None:
        """Make ``method`` raise ``exc`` on its next and every later call."""
        self._failures[method] = exc

    def override_generate(self, route: str, text: str) -> None:
        """Return ``text`` verbatim for the named route (see :data:`ROUTES`)."""
        known = {name for name, _marker, _builder in ROUTES}
        if route not in known:
            raise ValueError(f"Unknown route {route!r}; expected one of {sorted(known)}.")
        self._generate_overrides[route] = text

    def reset(self) -> None:
        self.calls.clear()
        self.unrouted_prompts.clear()
        self._failures.clear()
        self._generate_overrides.clear()
        self._optimized_prompt = DEFAULT_OPTIMIZED_PROMPT
        self._stream_chunks = None

    # ── Convenience accessors ─────────────────────────────────────────────

    @property
    def optimized_prompt(self) -> str:
        return self._optimized_prompt

    @property
    def stream_chunks(self) -> list[str]:
        if self._stream_chunks is not None:
            return list(self._stream_chunks)
        # Split on whitespace but keep it, so joining the deltas reproduces
        # _optimized_prompt byte for byte — the property the streaming tests
        # compare against the blocking response.
        words = self._optimized_prompt.split(" ")
        return [words[0]] + [f" {word}" for word in words[1:]]

    def calls_to(self, method: str) -> list[RecordedCall]:
        return [call for call in self.calls if call.method == method]

    # ── BaseLLMProvider implementation ────────────────────────────────────

    def _record(self, method: str, prompt: str, kwargs: dict[str, Any]) -> RecordedCall:
        call = RecordedCall(method=method, prompt=prompt, kwargs=dict(kwargs))
        self.calls.append(call)
        failure = self._failures.get(method)
        if failure is not None:
            raise failure
        return call

    async def analyze_prompt(self, prompt: str, **kwargs) -> PromptAnalysisResult:
        self._record("analyze_prompt", prompt, kwargs)
        return PromptAnalysisResult(
            clarity=9.0,
            context=8.0,
            specificity=8.0,
            constraints=6.0,
            output_structure=6.0,
            strengths="Clear objective.",
            weaknesses="No worked example.",
            recommendations="Add one example.",
            grade=STUB_ANALYSIS_GRADE,
        )

    async def optimize_prompt(
        self,
        prompt: str,
        template_id: str,
        **kwargs,
    ) -> PromptOptimizationResult:
        self._record("optimize_prompt", prompt, kwargs)
        return PromptOptimizationResult(
            optimized_prompt=self._optimized_prompt,
            template_id=template_id,
            score=8.5,
            metadata={"stub": True, "template_id": template_id},
        )

    async def optimize_prompt_stream(self, prompt: str, **kwargs) -> AsyncIterator[str]:
        self._record("optimize_prompt_stream", prompt, kwargs)
        for chunk in self.stream_chunks:
            yield chunk

    async def generate(self, prompt: str, **kwargs) -> GenerationResult:
        call = self._record("generate", prompt, kwargs)
        for name, marker, builder in ROUTES:
            if marker in prompt:
                call.route = name
                override = self._generate_overrides.get(name)
                text = override if override is not None else builder(prompt)
                return GenerationResult(text=text, metadata={"stub_route": name})

        self.unrouted_prompts.append(prompt)
        return GenerationResult(
            text=f"{UNROUTED_MARKER}\n{prompt[:200]}",
            metadata={"stub_route": None},
        )

    async def health_check(self) -> HealthCheckResult:
        self._record("health_check", "", {})
        return HealthCheckResult(healthy=True, details="stub provider")
